import { Dimensions } from 'react-native';

const screenWidth = Dimensions.get('window').width;

export const themeColors = {
  bg: '#D8B7FF',  
  textPrimary: '#FFFFFF', 
  buttonText: '#000000',  
  buttonBg: '#FFD700', 
  textSecondary: '#FFFFFF',  
  linkText: '#FFD700',
  inputBackground: '#F5F5F5', 
  inputBorder: '#ccc',        
  placeholderText: '#999',
};

export const themeStyles = {
  loginScreen: {
    backButton: {
      position: 'absolute' as const,
      top: 40,
      left: 20,
      backgroundColor: themeColors.buttonBg,
      padding: 10,
      width: 50,
      height: 50,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
    },
    image: {
      width: 300,
      height: 200,
      marginBottom: 15,
    },
    whiteBackground: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      marginTop: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    formContainer: {
      paddingHorizontal: 20,
      paddingVertical: 30,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold' as const,
      color: '#333',
      marginBottom: 5,
    },
    input: {
      width: screenWidth - 40,
      height: 40,
      borderWidth: 1,
      borderColor: themeColors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      marginBottom: 15,
      backgroundColor: themeColors.inputBackground,
    },
    forgotPassword: {
      fontSize: 14,
      color: themeColors.linkText,
    },
    loginButton: {
      backgroundColor: themeColors.buttonBg,
      paddingVertical: 15,
      borderRadius: 10,
      alignItems: 'center' as const,
      marginTop: 0,
    },
    loginButtonText: {
      fontSize: 18,
      fontWeight: 'bold' as const,
      color: themeColors.buttonText,
    },
    orText: {
      fontSize: 16,
      fontWeight: 'bold' as const,
      color: '#000',
      textAlign: 'center' as const,
      marginTop: 20,
      marginBottom: 20,
    },
    socialButtonsContainer: {
      flexDirection: 'row' as const,
      justifyContent: 'space-around' as const,
      marginHorizontal: 50,
      marginBottom: 0,
    },
    socialButton: {
      width: 50,
      height: 50,
      borderRadius: 15,
      backgroundColor: '#eee',
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    socialIcon: {
      width: 30,
      height: 30,
    },
    signupContainer: {
      flexDirection: 'row' as const,
      justifyContent: 'center' as const,
      marginTop: 5,
    },
    signupText: {
      fontSize: 14,
      color: '#999',
    },
    signupLink: {
      fontSize: 14,
      color: themeColors.linkText,
      fontWeight: 'bold' as const,
    },
  },
  signupScreen: {
    whiteBackground: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      marginTop: -20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    formContainer: {
      paddingHorizontal: 20,
      paddingVertical: 30,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold' as const,
      color: '#333',
      marginBottom: 5,
    },
    input: {
      width: screenWidth - 40,
      height: 40,
      borderWidth: 1,
      borderColor: themeColors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      marginBottom: 15,
      backgroundColor: themeColors.inputBackground,
    },
    loginButton: {
      backgroundColor: themeColors.buttonBg,
      paddingVertical: 15,
      borderRadius: 10,
      alignItems: 'center' as const,
      marginTop: 15, 
    },
    orText: {
      fontSize: 16,
      fontWeight: 'bold' as const,
      color: '#000',
      textAlign: 'center' as const,
      marginTop: -15,
      marginBottom: 0,
    },
    socialButtonsContainer: {
      flexDirection: 'row' as const,
      justifyContent: 'space-around' as const,
      marginHorizontal: 50,
      marginTop: 15,
      marginBottom: 20,
    },
    socialButton: {
      width: 50,
      height: 50,
      borderRadius: 15,
      backgroundColor: '#eee',
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    signupContainer: {
      flexDirection: 'row' as const,
      justifyContent: 'center' as const,
      marginTop: 5,
    }, 
    signupText: {
      fontSize: 14,
      color: '#999',
    },
    signupLink: {
      fontSize: 14,
      color: themeColors.linkText,
      fontWeight: 'bold' as const,
    },
  },
};